### ISSUE TITLE
Install os3 error

### ISSUE THREAD

**Issue by ChengFuWeiWei** [Avian688/os3#4]
My Environment:
Ubuntu VM `20.04`
Omnetpp `6.0.`
inet `4.4.1`
After I build the Makefile with following command:
```
opp_makemake --make-so -f --deep -KINET4_4_PROJ=$HOME/omnetpp-6.0/satellite_workspace/inet4.4 -DINET_IMPORT -I/home/linuxbrew/.linuxbrew/include/curl '-I$(INET4_4_PROJ)/src' '-L$(INET4_4_PROJ)/src'  -lcurl '-lINET$(D)'
```
I got this error
```
Creating shared library: ../out/clang-release/src/libos3.so
ld.lld: error: unable to find library -lINET
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
 I installed inet through the IDE by going help->Install Simulation Models->INET version 4

**Comment by Avian688** [comment]
This should work. Ensure that you have built INET and it works correctly. The error implies that the INET library cannot be found, so there must be something wrong with the INET reference - double-check that the path is correct. You could also automatically build the project through the IDE and see if that resolves anything.
