### ISSUE TITLE
open os3/simulations/SatSGP4/omnetpp.ini question

### ISSUE THREAD

**Issue by jinshushi** [Avian688/os3#5]
when i open terminal and wirte `opp_run -m -l ../../src/os3 omnetpp.ini`
and set up inifile confuration is SatSGP4
The confirm interface displays
`No 'hasVisualizer' function accepting 0 argument(s) was found, at /home/test/omnetpp-6.0/samples/os3/simulations/SatSGP4/SatSGP4.ned:17, at /home/test/omnetpp-6.0/samples/os3/simulations/SatSGP4/SatSGP4.ned:17 -- in module (omnetpp::cModule) SatSGP4 (id=1), during network setup`
I want to ask if I need to manually set this file

**Comment by Avian688** [comment]
This is most likely will need a slight change due to the new INET version. I will provide a quick fix within the next five minutes. Let me know if this fixes it!

**Comment by jinshushi** [comment]
Yes, thank you very much for your help. After using the updated file, the file `os3/simulations/SatSGP4/omnetpp.Ini` can be opened, so I think `SatSGP4` in your other project `leosatellites` also has the same problem.

**Comment by Avian688** [comment]
No problem. Shouldn't be an issue with the leosatellites as I had already made this fix. Let me know if you have any other issues and ill be more than happy to help!
________________________________
